### PR TITLE
Add support for orders & invoice

### PR DESCRIPTION
**Pull request by viezel**
- Add support for orders & invoice
- phpunit and unit tests

### CODE REVIEW

**Comment by viezel** [comment]
@sabas ready for review

**Comment by davidvandertuijn** [comment]
Quick suggestions:
- Reference to unece.org documentation instead of stylusstudio.com
- Use mixed in @param mixed $var when type is unknown ?

**Comment by viezel** [comment]
@davidvandertuijn sure ill change the reference. 
Regarding the mixed - well if you ask me it would rather go full strict type, but maybe to big of a refactor. So where do you want the change?

**Comment by sabas** [comment]
Thank you @viezel, I'll try to merge this night..

Just to ask also to @davidvandertuijn I pulled the changes in my client code some days ago and I noticed it failed with a type error when providing arrays with ints as it was annotated with string in the parameters, so I changed the default values from null to the previous value as string (15th march commit)

Do you want access to the repository or to the org?

**Comment by viezel** [comment]
Sure @sabas That would be neat to gain access. Then I could setup travis to automatically run tests for this

**Comment by viezel** [comment]
@sabas thanks for merging it in.
can you grant me access to the repo, so I can tag the release so we follow semvar.

**Comment by sabas** [comment]
@viezel done please try

**Pull request merged**
